# Generated by Django 4.2.1 on 2023-06-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0004_alter_vacations_vacid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('id', models.CharField(max_length=20, primary_key='True', serialize=False)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
    ]
