# Generated by Django 4.2.1 on 2023-06-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0007_alter_employee_adminid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='adminID',
            field=models.CharField(max_length=20),
        ),
    ]
